### PR TITLE
Add OpenWRT, Thali, JXcore

### PR DESCRIPTION
**Pull request by obastemur**
Adding list of related links given below:
- Thali - Framework for connected devices
- Basics of embedding JXcore
- Bundle JXcore for OpenWRT (ARM, mipsel) Memory: 16Mb+

### CODE REVIEW

**Comment by embeddednodejs** [comment]
Thanks for the links.
I had heard of JXCore before.

When I remember correctly, the project tries to run JavaScript directly on an embedded operating system, like Android or iOS?

A while back, I was playing with a board that was running Android: http://riotboard.org/

Any chance to have some more how-to's on how JXCore can run on maker boards, e.g. RaspberryPi or that RiotBoard?

**Comment by obastemur** [comment]
Thanks for this very useful list!

Binaries are available for both RiotBoard (Android ARM), and RaspberryPi (Debian - ARM) http://jxcore.com/downloads/

**Comment by embeddednodejs** [comment]
Ok, then to understand better: [JXCore](http://jxcore.com/home/) does not aim to replace the OS layer, but is built on top of that. The Node.js runtime has around 50MB to get e.g. a basic web server going. Does JXCore aim to replace the Node.js runtime on embedded systems, because it is smaller/more optimized towards embedded Linux?

**Comment by embeddednodejs** [comment]
PS the links will be on the site when I have time for the next build and release of the site. Probably some time tonight.

**Comment by obastemur** [comment]
> Ok, then to understand better: JXCore does not aim to replace the OS layer, but is built on top of that. The Node.js runtime has around 50MB to get e.g. a basic web server going. Does JXCore aim to replace the Node.js runtime on embedded systems, because it is smaller/more optimized towards embedded Linux?

Indeed, using JXcore It's not a problem to host a fully functional chat server on an OpenWRT powered WiFi router with 16Mb memory. Current aim is to reach below 1Mb (add another JS engine, replace openssl etc.)

AFAIK node.js never been there hence JXcore is not replacing anything. JXcore makes it possible to run node apps on wide range of devices and platforms. 

Upcoming 0.3.1.0 release also supports Win10 IoT. 

> PS the links will be on the site when I have time for the next build and release of the site. Probably some time tonight.

Sounds great and thanks for your support

**Comment by embeddednodejs** [comment]
> to host a fully functional chat server on an OpenWRT powered WiFi router with 16Mb memory.  Current aim is to reach below 1Mb (add another JS engine, replace openssl etc.)

Thanks. That sounds nice for e.g. a multimedia server to serve photos to a TV, and have other devices act as user agents. I'll give that a try when I have time. Also, I'll check if I can get it running on some embedded board. I guess: http://jxcore.com/multithreaded-javascript-tasks/#post-1091 shows the main ideas of running a web server.

**Comment by obastemur** [comment]
> I guess: http://jxcore.com/multithreaded-javascript-tasks/#post-1091 shows the main ideas of running a web server.

Nothing special is needed. You must be able to run any node.js apps as is.

**Comment by mulderp** [comment]
This is great. I am running JXcore on a Galileo now, and it works great.

I downloaded this:

  Debian ia32 (V8)  4.38 MB Download    7b397c9dca525ab8adcb1e019621df1c52ce32ec

**Pull request merged**
